name = "manolito-forestal"
main = "src/index.js"
compatibility_date = "2024-07-25"

workers_dev = true

[vars]
OPENROUTER_MODEL = "meta-llama/llama-3.1-70b-instruct"

[ai]
binding = "AI"

[assets]
directory = "./public"
binding = "ASSETS"

[[routes]]
pattern = "manolitoforestal.space"
custom_domain = true

[[routes]]
pattern = "www.manolitoforestal.space"
custom_domain = true
